# Generated by Django 5.1.1 on 2024-10-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='alias',
            field=models.CharField(default='sem nome', max_length=255),
            preserve_default=False,
        ),
    ]
