# Generated by Django 5.1.1 on 2024-10-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_pdffile_alias'),
        ('groups_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='groups_files.groupfile'),
            preserve_default=False,
        ),
    ]
